feat: test debug log

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -38,7 +38,7 @@ jobs:
         with:
           node-version: ${{ matrix.node-version }}
           cache: 'npm'
-      - name: Install packages
+      - name: Install dependencies
         run: npm ci
       - name: Validate code format
         run: npm run prettier:check
@@ -46,3 +46,7 @@ jobs:
         run: npm run lint
       - name: Validate all commits
         run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
+       - name: Debug echo
+        run: |
+          filename="MY_FILE.TXT"
+          echo "::error::Filename $filename doesn't match possible files" && exit 1
